/**
 * Shared sample loading module.
 * Loads instrument samples from self-hosted files in /samples/.
 */

/** Manifest file structure generated by extract-samples.py */
interface SampleManifest {
  instrument: string
  velocityLayers?: number[]
  notes: string[]
}

/**
 * Sharp-to-flat mapping for note names.
 * Sample files use flat notation (Db, Eb, etc.) to avoid # in URLs.
 */
const SHARP_TO_FLAT: Record<string, string> = {
  'C#': 'Db',
  'D#': 'Eb',
  'F#': 'Gb',
  'G#': 'Ab',
  'A#': 'Bb',
}

/**
 * Convert a note name with sharps (e.g. "C#4") to flat notation (e.g. "Db4").
 */
export function toFlatNoteName(note: string): string {
  const match = note.match(/^([A-G]#?)(\d+)$/)
  if (!match) return note
  const [, name, octave] = match
  const flat = SHARP_TO_FLAT[name]
  return flat ? flat + octave : note
}

/** URL map and base URL for a single velocity layer. */
export interface LayerSampleData {
  urls: Record<string, string>
  baseUrl: string
  velocity: number
}

export interface SampleData {
  layers: LayerSampleData[]
}

/**
 * Load sample data for an instrument from local /samples/ directory.
 * Fetches the instrument's manifest.json and returns URLs for each velocity layer.
 * Supports both legacy (no velocity layers) and new multi-layer manifests.
 */
export async function loadSampleData(sampleName: string): Promise<SampleData> {
  const baseUrl = `/samples/${sampleName}/`
  const manifestUrl = `${baseUrl}manifest.json`

  const response = await fetch(manifestUrl)
  if (!response.ok) {
    throw new Error(
      `Failed to load sample manifest: ${manifestUrl} (${response.status}). Run "python scripts/extract-samples.py" to generate samples.`,
    )
  }

  const manifest: SampleManifest = await response.json()

  const velocityLayers = manifest.velocityLayers ?? [0]
  const isMultiLayer = manifest.velocityLayers != null

  const layers: LayerSampleData[] = velocityLayers.map((velocity) => {
    const urls: Record<string, string> = {}
    for (const note of manifest.notes) {
      urls[note] = isMultiLayer ? `${note}_v${velocity}.ogg` : `${note}.ogg`
    }
    return { urls, baseUrl, velocity }
  })

  return { layers }
}
